# Generated by Django 4.1.5 on 2023-01-31 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": []},
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
        migrations.AddField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(to="blog.post"),
        ),
        migrations.AddField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
