# Generated by Django 4.1.5 on 2023-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_remove_category_posts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(to="blog.post"),
        ),
    ]
