# Generated by Django 4.1.5 on 2023-02-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_post_category_category_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
